[package]
name = "operating-system"
version = "0.1.0"
edition = "2024"

[dependencies]
uefi = "0.36.1"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[workspace]
members = ["disk_image"]