[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-unknown-uefi]
rustflags = [
  "-C", "link-args=/ENTRY:efi_main",
  "-C", "link-args=/SUBSYSTEM:EFI_APPLICATION",
]
